name: Bump version & tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver (e.g. 0.3.2 or 0.3.2-beta.1)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate semver
        id: semver
        run: |
          V="${{ inputs.version }}"
          if [[ ! "$V" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z\.\-]+)?$ ]]; then
            echo "Invalid semver: $V" >&2
            exit 1
          fi
          echo "version=$V" >> "$GITHUB_OUTPUT"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install jq and cargo-edit
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          cargo install cargo-edit

      - name: Bump package.json
        run: |
          V="${{ steps.semver.outputs.version }}"
          node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('package.json','utf8'));p.version='${V}';fs.writeFileSync('package.json',JSON.stringify(p,null,2)+'\n')"

      - name: Bump src-tauri/tauri.conf.json
        run: |
          V="${{ steps.semver.outputs.version }}"
          jq --arg v "$V" '
            (.version        |= $v)
          ' src-tauri/tauri.conf.json > /tmp/tauri.conf.json
          mv /tmp/tauri.conf.json src-tauri/tauri.conf.json

      - name: Bump src-tauri/Cargo.toml
        run: |
          V="${{ steps.semver.outputs.version }}"
          cargo set-version --manifest-path src-tauri/Cargo.toml "$V"

      - name: Commit and tag
        run: |
          V="${{ steps.semver.outputs.version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json src-tauri/tauri.conf.json src-tauri/Cargo.toml
          git commit -m "chore(release): v$V"
          git tag "v$V"
          git push origin HEAD
          git push origin "v$V"
