name: Publish draft release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver (e.g. 0.3.2 or 0.3.2-beta.1)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate semver
        id: semver
        run: |
          V="${{ inputs.version }}"
          if [[ ! "$V" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z\.\-]+)?$ ]]; then
            echo "Invalid semver: $V" >&2
            exit 1
          fi
          echo "version=$V" >> "$GITHUB_OUTPUT"
      - name: Set tag output
        id: meta
        run: echo "tag=v${{ steps.semver.outputs.version }}" >> "$GITHUB_OUTPUT"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install jq and cargo-edit
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          cargo install cargo-edit

      - name: Bump package.json
        run: |
          V="${{ steps.semver.outputs.version }}"
          node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('package.json','utf8'));p.version='${V}';fs.writeFileSync('package.json',JSON.stringify(p,null,2)+'\n')"

      - name: Bump src-tauri/tauri.conf.json
        run: |
          V="${{ steps.semver.outputs.version }}"
          jq --arg v "$V" '
            (.version        |= $v)
          ' src-tauri/tauri.conf.json > /tmp/tauri.conf.json
          mv /tmp/tauri.conf.json src-tauri/tauri.conf.json

      - name: Bump src-tauri/Cargo.toml
        run: |
          V="${{ steps.semver.outputs.version }}"
          cargo set-version --manifest-path src-tauri/Cargo.toml "$V"

      - name: Commit and tag
        run: |
          V="${{ steps.semver.outputs.version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json src-tauri/tauri.conf.json src-tauri/Cargo.toml
          git commit -m "chore(release): v$V"
          git tag "v$V"
          git push origin HEAD
          git push origin "v$V"

  verify-versions:
    name: Verify versions
    needs: bump
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.out.outputs.version }}
      tag: ${{ steps.out.outputs.tag }}
    steps:
      - name: Checkout updated code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump.outputs.tag }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Read and verify versions
        id: out
        run: |
          V="${{ needs.bump.outputs.version }}"
          TAG="v$V"
          echo "version=$V" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          PKG=$(node -p "require('./package.json').version")
          TAURI=$(node -p "JSON.parse(require('fs').readFileSync('src-tauri/tauri.conf.json','utf8')).version")
          PY='import tomllib,sys;print(tomllib.load(open("src-tauri/Cargo.toml","rb"))["package"]["version"])'
          CARGO=$(python3 -c "$PY")
          echo "Tag:             $TAG"
          echo "Version:         $V"
          echo "package.json:    $PKG"
          echo "tauri.conf.json: $TAURI"
          echo "Cargo.toml:      $CARGO"
          if [ "$PKG" != "$V" ] || [ "$TAURI" != "$V" ] || [ "$CARGO" != "$V" ]; then
            echo "❌ Version mismatch; make sure all files match $V"
            exit 1
          fi

      - name: Cache node_modules (primary)
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
          key: verify-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        continue-on-error: true

  build:
    name: Build ${{ matrix.platform }}
    needs: verify-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux-x86_64
            os: ubuntu-latest
          - platform: macos-universal
            os: macos-latest
          - platform: windows-x86_64
            os: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.verify-versions.outputs.tag }}
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Linux build deps for Tauri/Wry/WebKitGTK
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libglib2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install JS deps
        run: pnpm install --frozen-lockfile

      # Optional: cache cargo registry/builds to speed repeat builds
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      # Build & Release with Tauri action
      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ needs.verify-versions.outputs.version }}
          releaseName: "Quantus Miner v${{ needs.verify-versions.outputs.version }}"
          releaseBody: "Automated Tauri release for v${{ needs.verify-versions.outputs.version }}"
          releaseDraft: true
          prerelease: ${{ contains(needs.verify-versions.outputs.version, '-') }}
          # If you want universal mac builds and NSIS on Windows, tauri-action auto-detects from config

      # Portable, user-space artifacts (no root/admin required)
      - name: Package Linux portable tar.gz
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -C src-tauri/target/release -czf quantus-miner-${{ needs.verify-versions.outputs.version }}-linux-x86_64.tar.gz quantus-miner

      - name: Upload Linux portable tar.gz
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: quantus-miner-${{ needs.verify-versions.outputs.version }}-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Windows portable zip
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $Version = "${{ needs.verify-versions.outputs.version }}"
          $Out = "quantus-miner-$Version-windows-x86_64.zip"
          Compress-Archive -Path "src-tauri\target\release\quantus-miner.exe" -DestinationPath $Out -Force

      - name: Upload Windows portable zip
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: quantus-miner-${{ needs.verify-versions.outputs.version }}-windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
